//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCustomerEmployeeOrder
    {
        public int UserID { get; set; }
        public int Customer_ID { get; set; }
        public string FullName { get; set; }
        public int Order_ID { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Expr1 { get; set; }
        public string Status { get; set; }
    }
}
