//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginalOrder
    {
        public int Order_ID { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string UserName { get; set; }
        public int UserID { get; set; }
        public int CustomerID { get; set; }
        public string Customer_Name { get; set; }
        public string Status { get; set; }
    }
}
